- README.md
- ansible/playbooks/install-redpanda.yml
- ansible/playbooks/start-redpanda.yml
There was no default for advertise_public_ips, so it would fail unless
the user specified this parameter. Also updated to use the new package
repo and drop the requirement for a token.
> Set default for advertise_public_ips and use packages.vectorized.io

- .gitignore
- README.md
- ansible/playbooks/install-node-deps.yml
- ansible/requirements.yml
- gcp/cluster.tf
- gcp/readme.md
- gcp/vars.tf
- hosts.ini
- templates/hosts_ini.tpl
- Removes hard-coded 'project_name' and 'credentials' from GCP
configuration.
- Introduces a 'project_name' variable to hold GCP project name.
- Updates gcp/README with instructions on how to setup credentials and
to document the new project_name variable
> gcp: fix for GCP terraform module

- aws/cluster.tf
Changes in the GCP terraform script also included changes to the
host.ini template however, aws was not updated. This fixes this.
> Fixed variables in AWS terraform script

- templates/hosts_ini.tpl
Previously disabling monitoring resulted in a corrupted line ( without any IPs ) leading to errors when ansible tried to copy grafana dashboards onto the monitor node.
eg. 
```
[redpanda]
54.218.44.241 ansible_user=ubuntu ansible_become=True private_ip=172.31.54.48 id=0
34.219.213.230 ansible_user=ubuntu ansible_become=True private_ip=172.31.62.102 id=1
34.215.46.70 ansible_user=ubuntu ansible_become=True private_ip=172.31.55.29 id=2
[monitor]
ansible_user=ubuntu ansible_become=True private_ip=
```
```
PLAY [monitor] *******************************************************************************************************************************************************************************
[WARNING]: Unhandled error in Python interpreter discovery for host ansible_user=ubuntu: Failed to …
```
> ansible: Only run playbooks when monitoring is enabled

- ansible/playbooks/prepare-data-dir.yml
Until now due to initialization inside a loop the variable remained uninitialized if no nvme nodes were found.
> Allow installation on instances without an nvme drive

- aws/cluster.tf
The use of timestamp() as part of the deployment ID means that,
in effect, the deployment ID changes every time a plan is created.
Instead, we use time_static, which is the recommended way to
introduce timestamps into a resouce: the timestamp is genenated only
when the resource is created in the first place.
Fixes #42.
> Prevent deployment ID from changing every plan

- aws/provider.tf
In my last change, I forgot to add the "time" provider to the
provider.tf list. This still works because terraform also has
an autodetect mode for providers, but the recommended way is
to use this file.
Also sorted the providers list to keep merge conflicts to a minimum
in the future.
> Add time to the providers list

- ansible/playbooks/start-redpanda.yml
Using:
var | d() | bool
Handles the usual cases where we set var on the command line using
string values, and also handles correctly typed values (e.g., if
var actually is a boolean).
Fixes #50.
> use bool filter to coerce boolean vars

- ansible/playbooks/start-redpanda.yml
Enabling Kafka queue depth controls significantly help reduce producer ack latency when disks reach write saturation. This is especially prevalent for cloud deployments with persistent remote storage because of lower iops and bandwidth.
> Enable Kafka queue depth control by default

- ssh-bootstrap.yml
- templates/sudoers.j2
As mentioned in ssh-bootstrap.yml:
This is a utility for developers and is not intended to be used in
production. Please review all the commands before using. Make sure you
use unique secrets and keep them safe.
> Add ssh user bootstrap utility playbook.

- ansible/playbooks/start-redpanda.yml
Curently QDC (queue depth control) is enabled by default, but as
this can be detrimental to performance this we now disable it
for now.
> Remove QDC from ansible deployment

- README.md
- ansible/playbooks/prepare-data-dir.yml
This option will be enabled at runtime via
`--extra-vars` when running the ansible playbook.
When using an attached disk on an
ephemeral-disk-instance the mounts might be
deleted if a node is restarted/stopped, so we are
changing the ftsab options to:
```
fs_freq/dump 1 - enables dump (if installed)
for this filesystem.
fs_passno    2 - filesystem checker order,
should be 2 for non-root FS if
we want fscheck to check/repair
our fs.
```
This will enable us to repair the mount if the
ephemeral-disk-instance mess up the mount at boot
time.
Tested in Azure L Series VM.
> Change mount fstab options for attached disks

- ansible/playbooks/deploy-prometheus-grafana.yml
- ansible/playbooks/start-redpanda.yml
- aws/cluster.tf
- aws/readme.md
- aws/vars.tf
- templates/hosts_ini.tpl
Tristan has an initial PR for implementing HA and rack awareness across AWS, GCP, and Azure. But during testing we ran into some issues in Azure that may require changes. At the same time a customer requires rack awareness in AWS.
This PR focuses on implementing this feature only in the AWS implementation. This will give us time to work through the changes needed for other cloud providers without impacting AWS customers. #82 is not closed with this PR as that ticket includes all cloud providers.
I've also included a small fix for prometheus so it properly starts (a dependency was missing from the Ubuntu distro).
In order to test, change this variable to true: https://github.com/redpanda-data/deployment-automation/blob/1a8f8f3fd799808b3acc3a06989d64abc91b6d9f/aws/vars.tf#L12-L16
Then run …
> Enable high availability and rack awareness on AWS

- .gitignore
- ansible/playbooks/tls/install-certs.yml
- aws/cluster.tf
- aws/vars.tf
This PR addresses a breaking issue with:
> ansible/playbooks/tls/install-certs.yml
Where it overwrites required configuration that was previously set with RPK config by the initial redpanda install scripts.
Non critical changes:
It additionally adds optional features for EBS volume creation to create gp3 or other types of EBS volumes, in multiples, and properly RAID-0 them.
> Correct issue with ansible tls install script and add features for variable EBS gp3 volume creation

- README.md
- ansible/playbooks/roles/redpanda_broker/defaults/main.yml
- ansible/playbooks/roles/redpanda_broker/tasks/install-redpanda.yml
Allow use of staging repo and specification of specific redpanda versions.
Updated README to include details of defaults
> Introduce logic to support use of unstable versions

- ansible/playbooks/roles/redpanda_broker/templates/configs/defaults.j2
We included two settings for both advertised_*_apis, one of which incorrectly pointed at the private IP rather than the advertised IP.
> ansible: fix advertised apis

- ansible/playbooks/roles/redpanda_broker/templates/configs/defaults.j2
Introduced by #98 which was a duplicate of the same value (one correct, one incorrect)
> Remove erroneous list element from advertised_rpc_api

- ansible/playbooks/install-node-deps.yml
- ansible/playbooks/roles/redpanda_broker/tasks/install-redpanda.yml
- ansible/requirements.yml
ansible 2.14+ doesn't support warn parameters for ansible.builtin.shell and causes playbook runs to fail.
This fixups the code where we use it explicitly. Complicating this issue, is the fact that the cloudalchemy.node_exporter module also has the same issue, but is no longer maintained. I've switched us over to geerlingguy's fork which is more recently updated and fixes the underlying problem.
> Bugfix/issue 103/shell cmd warn

- azure/cluster.tf
- azure/outputs.tf
- azure/vars.tf
our global variable names should be unified across clouds to simplify administration of the TF configurations for users, especially if they end up as multi-cloud implementations at some point. Azure had it different for no discernible reason.
> fix: unify public_key_path variable name

- .gitignore
Let's make sure to never track these override files in the aws, gcp, and azure directories for folks having some standard variable overrides used for their dev environments. We don't want those sneaking in accidentally.
> Make git ignore _override.tf files for locally modifying tf vars

- .buildkite/scripts/runtask.sh
run script was not exiting with the correct exit code, allowing failed builds to result in success
> fix run script

- ansible/playbooks/roles/redpanda_broker/templates/configs/tiered_storage.j2
This seems to be a problem introduced when handling a merge conflict (or possibly with the tiered storage PR itself). The variable was still set as the older (now renamed) `aws_region`.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204218351695001
> Update tiered_storage.j2 to use correct cloud_storage_region

- Taskfile.yaml
- ansible/deploy-prometheus-grafana.yml
Install deps for node exports when standing up prom, not just as part of the standard cluster build.
Also fix a minor but annoying issue with install-rpk task asking for permission to overwrite
Tested in AWS by 
* standing up cluster
* applying basic cluster playbook (soon to be resolved issue with rpk not offering a way to pass truststore to admin for metrics stuff means this won't work with TLS right now)
* applying prometheus playbook
* going to prom page and running various queries successfully
> add playbook install deps for node exporter

- ansible/provision-node.yml
- ansible/provision-tls-cluster.yml
Since we're removing these as defaults from the role they should be provided in the playbook. It might be sensible to set version to blank to ensure the user MUST select it.
related to https://github.com/redpanda-data/redpanda-ansible-collection/pull/8
> Put needed vars in playbook

- aws/cluster.tf
the policy we create on behalf of the user for allowing the instance to access the s3 bucket appears to be missing a resource required by Redpanda needed for ListBucket. 
See internal discussion at https://redpandadata.slack.com/archives/C02BDN76HUK/p1683670439226129
> add missing resourced needed for ListBucket

- .buildkite/pipeline.yml
- .buildkite/scripts/standup-tiered-storage.sh
- .buildkite/scripts/standup-tls.sh
- Dockerfile_FEDORA
- Dockerfile_UBUNTU
- Taskfile.yaml
- aws/vars.tf
- requirements.yml
This is a minor testing improvement to support ongoing airgap work in [RAC](https://github.com/redpanda-data/redpanda-ansible-collection)
added ansible.posix to required collections
added distro and prefix as settable values to the pipeline scripts 
corrected taskfile collection install
fixed vars comments incorrectly referring to var.client_distro 
added fedora testing for tiered/tls to pipeline
fixed an uncaught error code for keygen
> add support for fedora testing + fix bugs

- azure/cluster.tf
- azure/network.tf
- azure/vars.tf
Simple change to bring the name and type of the availability zone parameter to align it with the AWS and GCP implementations.
> Align Azure availability zone parameter name

- README.md
- Taskfile.yaml
- aws/main.tf
made it easier for users to pass in information necessary to start up a cluster with TF
standardized the inventory file declaration in taskfile to a single variable because why
> fix for aws standard main.tf

- aws/main.tf
Fixes an issue that can occur with a missing type defaulting to string rather than dynamically assigning list(string)
> fix missing type

- .buildkite/pipeline.yml
- .buildkite/scripts/test-basic-cluster.sh
- .buildkite/scripts/test-tiered-storage-cluster.sh
- .buildkite/scripts/test-tls-cluster.sh
- Taskfile.yaml
Registry is enabled by default now, so we want to
test this for now using curl.
Once `rpk registry` is released we need to change
this test to use rpk.
> test: add basic cluster test and add registry bits

- ansible/provision-tls-cluster.yml
For whatever reason, looks like the sysctl role was never included in the tls playbook
> Add sysctl role else TLS clusters won't start

- .buildkite/pipeline.yml
fixes https://redpandadata.atlassian.net/browse/PESDLC-1526
buildkite currently reads secrets from the s3 secrets bucket into env vars for use by the pipeline. these secrets were copied into aws secretsmanager and this PR updates the pipeline so it uses the [seek-oss/aws-sm](https://github.com/seek-oss/aws-sm-buildkite-plugin) plugin to read the secrets from aws secretsmanager for the https://buildkite.com/redpanda/deployment-automation pipeline. there is no functionality change because the env vars are kept the same name and values.
> buildkite: retrieve secrets from aws sm

- .github/workflows/ansible-lint.yaml
- Makefile
- README.md
- ansible/airgap/bundle-deb-for-airgap.yml
- ansible/airgap/bundle-rpm-for-airgap.yml
- ansible/deploy-connect-tls.yml
- ansible/deploy-connect.yml
- ansible/deploy-console-tls.yml
- ansible/deploy-monitor-tls.yml
- ansible/deploy-monitor.yml
- ansible/operation-rolling-restart.yml
- ansible/provision-cluster-tiered-storage.yml
- ansible/provision-cluster-tls.yml
Adds rolling restart functionality. Can be run against a cluster to restart all nodes in sequence without other changes.
> feat: add rolling restart

- .buildkite/pipeline.yml
- Makefile
- ansible/operation-apply-license.yml
Adds an operation to apply license separately + testing related to it.
> Adding License Testing for Tiered Storage

- requirements.yml
There's a bug in the latest grafana role that causes issues with deploying it as part of testing. I've pinned to 5.6.0 until they've resolved the issue
https://github.com/grafana/grafana-ansible-collection/issues/320
> fix: pin grafana version
