README.md, tasks/prepare-data-dir.yml
default to raid-0 since the target machine is i3.8xlarge
=> tasks/docs: default raid to true

README.md, cluster.tf, outputs.tf, templates/hosts_ini.tpl, vars.tf
Previously the host.ini file had to be manually edited, now terraform will auto generate this. The documentation has also been changed to reflect this change.
=> Auto generate the host.ini file

README.md, aws/cluster.tf, aws/readme.md, aws/vars.tf, gcp/cluster.tf
- Fixed examples for aws in readme.
- Fixed the updating of the hosts.ini from gcp/aws
- Updated the main readme.
=> Various Fixes

aws/cluster.tf, aws/outputs.tf, aws/readme.md, aws/vars.tf, templates/hosts_ini.tpl
- aws: readme tweaks.
- asw: readme tweaks
- aws: add AMI id for ubuntu hirsute build.
- aws: add support for provisioning blank client VMs
=> aws: provisioning for client VMs and README tweaks

.gitignore, README.md, azure/README.md, azure/cluster.tf, azure/network.tf, azure/outputs.tf, azure/provider.tf, azure/vars.tf, templates/hosts_ini.tpl
Reopening `feature/azure`. The previous PR #40 was merged but subsequently reverted #41 due to an issue with the `hosts_ini.tpl` template file in AWS and GCP. This has now been fixed by commit a6928e2f35dff5c89882579753883a858ec5c286.
=> Azure Terraform Configuration

ansible/playbooks/start-redpanda.yml
Otherwise, failures in anything other than the last line wil
be silently ignored.
Issue #49.
=> Use set -e in multi-line shell commands

aws/cluster.tf
A tag iam_username is created on resources such as instances with
name of the IAM user who ran terraform to create the resource.
Fixes #45.
=> Create a tag with IAM user on resources.

ansible/playbooks/install-redpanda.yml, ansible/playbooks/prepare-data-dir.yml, artifacts/.gitignore, artifacts/README.md
A convenient place to put things you want ignored by git, such as your
host inventory files.
=> Create artifacts/ directory, minor cleanups

ansible/playbooks/provision-node.yml, ansible/playbooks/start-redpanda.yml, aws/provider.tf, aws/readme.md, azure/README.md, azure/network.tf, azure/vars.tf
Old version of TF AWS provider had issues on M1.
New Ansible version [2.12.1] throws error for 'include'.
=> Update TF AWS Provider version & Ansible

ansible/playbooks/deploy-prometheus-grafana.yml, ansible/playbooks/install-node-deps.yml
Remove Kafka binaries, remove jdk install, change grafana to latest and update --prometheus-url to --metrics-endpoint
=> Remove java/kafka, update grafana version and rpk command

ansible/playbooks/deploy-prometheus-grafana.yml
Simple fix replacing apt/shell with package module
=> Change to non-OS specific package module

aws/cluster.tf, azure/outputs.tf, gcp/cluster.tf, templates/hosts_ini.tpl
Builds on Azure and GCP failing with missing variables.
=> Fix build errors on GCP and Azure with tiered storage.

ansible/playbooks/install-node-deps.yml
=> node_exporter_version expression needs to be in {{ }}

aws/cluster.tf, aws/provider.tf, aws/readme.md, aws/vars.tf, gcp/cluster.tf, gcp/outputs.tf
Added tag merging to support custom tags alongside our existing tags, fixed various formatting issues, cleaned up some deprecated formatting.
Added the GCP splat fixes in too since I missed them before.
=> various minor tweaks/changes to aws stuff

.buildkite/scripts/runtask.sh, Taskfile.yaml
also deleted dead code so i dont have to write a comment :joy:
using my email because vanta needs a registered email to track who owns stuff
=> fixed tagging for aws in cicd

gcp/readme.md
Just made a couple of changes to the readme to reflect what I see in vars.tf.  I think there may be a few additional changes needed in the readme but just want to try the PR process with these first.
=> Fixed a couple of errors in readme comparing with vars.tf

.buildkite/scripts/testcluster.sh
Adds an additional test that ensures we can safely consume from the topic.
=> Add consuming from topic

.buildkite/pipeline.yml, .buildkite/scripts/standup-tiered-storage.sh, .buildkite/scripts/standup-tls.sh, .buildkite/scripts/test-basic-cluster.sh, .buildkite/scripts/test-tiered-storage-cluster.sh, .buildkite/scripts/test-tls-cluster.sh, Dockerfile, README.md, Taskfile.yaml, ansible/provision-tiered-storage-cluster.yml, aws/cluster.tf, aws/s3.tf
Contains testing changes to incorporate tiered storage including an S3 bucket check,  a tiered storage playbook and fixes for template merging. Also incorporates some changes to the docker container to support running awscli.
=> Tiered Storage Improvements

azure/network.tf, azure/outputs.tf, azure/vars.tf
Added flags to allow public ip address creation to be suppressed, along with CIDR customisation.
=> Adding private network capability to Azure.

.buildkite/pipeline.yml, .buildkite/scripts/standup-cluster.sh, Taskfile.yaml, aws/main.tf
https://github.com/redpanda-data/redpanda-ansible-collection/issues/22
Fixes an issue our mdadm implementation has with is4gen.4xlarge instance types
=> fix for mdadm issues with larger instance types

ansible/airgap/provision-private-proxied-cluster-airgap-deb.yml, ansible/airgap/provision-private-proxied-cluster-airgap-rpm.yml, ansible/provision-basic-cluster.yml, ansible/provision-tiered-storage-cluster.yml, ansible/provision-tls-cluster.yml, ansible/proxy/provision-private-proxied-cluster.yml
Adds the sysctl setup role to the existing playbooks
=> feat: add sysctl_setup role
